name: Github Page # 名字随意 

on:
  push:
    branches:
      - master  # 私有仓库的默认分支名字 

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Tencent COS
        env:
          SECRET_ID: ${{ secrets.COS_TENCENT_SECRET_ID }}
          SECRET_KEY: ${{ secrets.COS_TENCENT_SECRET_KEY }}
          BUCKET: ${{ secrets.COS_TENCENT_BUCKET }}
          REGION: ap-beijing
        run: |
          sudo pip install coscmd
          coscmd config -a ${SECRET_ID} -s ${SECRET_KEY} -b ${BUCKET} -r ${REGION}
          coscmd upload -rs --delete ./ / -f
          

